### PR TITLE
Adapt to 400x240

### PR DESCRIPTION
**Pull request by asiekierka**
I'm not sure if this covers *everything*, but a quick playtest seems to imply that is the case - I am not sure about the ending screen, however.

Please note that the game map has not been adapted to 400x240, but rather offset in a 320x240 "window".

### CODE REVIEW

**Comment by nop90** [comment]
Why did you changed the screen size to 400pixel width?

Maybe to have a larger view of big rooms? Or maybe because you don't like stretched images?

I prefer to leave the original size stretched, cause I don't like images with black borders on size. And I'm used to stretched images from 320x240 to 400x240. In emulators is quite common.

So please don't be upset if I don't merge your commit to my version, I like it my way, but I'm happy someone makes it's custom mod to adapt the game to it's liking.

If you want to help, a tester of mine reported that the game hungs when the layer goes on the altar of the three artifact key (the artifact should fly to the player). I'm trying to fix this bug. 

Thanks.

**Comment by asiekierka** [comment]
@nop90 Because I feel the stretched image doesn't look particularly great, as it does not respect the aspect ratio. At the same time, a 320x240 image in the middle feels like wasting the valuable space of the top screen - and the screen is already quite small! Keep in mind that the original Meritous plays at a 640x480 resolution - 320x240 cropping is really tiny in comparison.

Also, I can look into it, I suppose.

**Comment by asiekierka** [comment]
By the way - I fixed the images and they no longer have black borders on the side. Where possible, I re-used the original assets; otherwise, I tried to make the borders more interesting. I still have to remove borders from the game map.

My TODO also includes adding 3D support to the game, but that might (probably will) require ditching SDL 1.2.

**Comment by asiekierka** [comment]
(Also, the borders referred solely to the "game map", that is the in-game "minimap" screen, not the actual gameplay)

**Comment by nop90** [comment]
Ok. Let's try the changes.

I also fixed the bug on the special object altar.

Thanks

**Comment by asiekierka** [comment]
https://github.com/asiekierka/Meritous-3ds/commit/695d32309ecc6b724f1ffc962fb8461fd218cfe8

Cherry-pick this as well - it makes the minimap 400x240, making the entire game "borderless" 400x240.

**Comment by nop90** [comment]
Thanks,
I'm submitting the resources for the CIA build. Forgot to add them last time.

If it's ok for you I'm going to credit you for the fixex on gbatemp with the next release (tonight probably)

**Comment by asiekierka** [comment]
It's alright with me, yes.

You might want to look into your SDL-3DS port causing the dreaded "triangle" issue on real hardware.

**Pull request merged**
